### PR TITLE
Fix linear interpolation in SimpleIndex.cpp

### PR DESCRIPTION
**Pull request by schoppmp**
To interpolate `f(x)` linearly between `f(x0)` and `f(x1)`, the [correct equation](https://en.wikipedia.org/wiki/Linear_interpolation) is `f(x) = 1 / (x1 - x0) * (x1 - x) * f(x0) + (x - x0) * f(x1)`. With `x1 - x0 = 1` and `diff := x - x0`, this means `f(x) = (1 - diff) * f(x0) + diff * f(x1)`.

### CODE REVIEW

**Comment by ladnir** [comment]
thanks, ill merge this soon.

**Comment by ladnir** [comment]
This is failing on debug build where [additional checks are performed](https://github.com/Visa-Research/volepsi/blob/main/volePSI/SimpleIndex.cpp#L276). The new bin sizes are too small.

What prompted this change?

**Comment by schoppmp** [comment]
The function is concave, so I would expect any linear interpolation to undershoot it. If you want the approximation to always be larger than the actual value, you could instead compute a tangent on the real function at each power of 2, but that would need the derivative of the exact function, as well as a new table. Not sure what other approaches there are to linearly overapproximate a concave function. 

Is the difference large?

**Comment by RindalVisa** [comment]
not totally sure but I think there have been some crashes as the bins overflow. whoops. 

I reverted but will try to look into it when time allows.

**Pull request merged**
